CREATE TABLE pd_basic_plan(

plan_code  varchar(4)  NOT NULL,
add_rate  float8, 
cover_cal  int4 ,
cover_term  int4,
hiv  varchar(1),
interest_rate  float8,
maturity_rate  float8,
max_premium  float8,
max_sum_insured  float8,
med  varchar(1),
mib  varchar(1),
min_premium  float8,
min_premium_pay  float8,
min_premium_pay_cal  varchar(1),
min_sum_insured  float8,
plan_name  varchar(255),
premium_cal  int4,
premium_term  int4,
start_date  timestamp,
status  varchar(1),
uw_app_rate  float8,
wp  varchar(1),
family_code  varchar(4) NOT NULL,
group_code  varchar(4) NOT NULL,
cal_age  varchar(1),
cal_sum_insured  varchar(1),
plan_no  varchar(10),
max_sum_ins_old  int8,
group_sum_ins_id  int8,
re_new_rate  float8,
dividend  varchar(1),
cv_type  varchar(2),
expire_date  timestamp,
plan_short_name  varchar(50),
require_pron_flag  varchar(1),
flag_display_insure  varchar(1),
digit_decimal  float8,
rounding_type  varchar(1),
cal_sumins_agentgate  varchar(1),
med_app_rate  float8,
flag_next_payment  varchar(1),
display_slip_ind  varchar(255),
max_sum_premium_total  float8,
freelook_period  int8,
mib_app_rate  float4,
claim_app_rate  float4,
agentgate_app_rate  float8,
cal_age_cover_term  varchar(1),
channel_code_as400 varchar(3),
med_app_type  varchar(30),
gio_flag  varchar(1),
med_doc_code  varchar(10)
);