-- public.dm_newcase_report definition

-- Drop table

-- DROP TABLE public.dm_newcase_report;

CREATE TABLE public.dm_newcase_report (
	id varchar(10) NOT NULL,
	region varchar(50) NULL,
	branch_code varchar(4) NOT NULL,
	branch_name varchar(50) NULL,
	policy_type varchar(20) NULL,
	policy_no varchar(20) NOT NULL,
	cust_id varchar(12) NULL,
	plan_code varchar(10) NULL,
	plan_name varchar(100) NULL,
	agent_code_7 varchar(7) NULL,
	agent_name varchar(100) NULL,
	"position" varchar(100) NULL,
	commission_first numeric(19,2) NULL,
	policy_status varchar(20) NULL,
	la_age varchar(5) NULL,
	effective_date_from date NULL,
	effective_date_to date NULL,
	sum_assured numeric(19,2) NULL,
	premium numeric(19,2) NULL,
	payment_mode numeric(19) NULL,
	last_pay_period_date varchar(20) NULL,
	la_name_surname varchar(100) NULL,
	id_no varchar(30) NULL,
	occupation_group varchar(100) NULL,
	occupation varchar(100) NULL,
	address varchar(150) NULL,
	subdistrict varchar(100) NULL,
	district varchar(100) NULL,
	province varchar(100) NULL,
	zipcode varchar(5) NULL,
	phone1 varchar(100) NULL,
	phone2 varchar(100) NULL,
	mobile1 varchar(100) NULL,
	mobile2 varchar(100) NULL,
	"period" varchar(10) NOT NULL,
	csv_created_date timestamptz NULL,
	csv_created_by varchar(20) NULL,
	"_audit_filename" varchar(255) NULL,
	"_audit_filemod" timestamptz NULL,
	"_audit_filesize" numeric(16) NULL,
	"_audit_created" timestamptz NULL,
	CONSTRAINT agpt_newcase_report_pk PRIMARY KEY (id, period, branch_code)
);